[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/courses"
  to = "https://benjisaiempire.com/courses"
  status = 200
  force = true

[[redirects]]
  from = "/courses/*"
  to = "https://benjisaiempire.com/courses/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/landing"
  to = "https://benjisaiempire.com/"
  status = 200
  force = true

[[redirects]]
  from = "/insider"
  to = "/insider/index.html"
  status = 200

[[redirects]]
  from = "/insider/*"
  to = "/insider/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
